name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Format Code
        run: go fmt ./pkg
  create_comment:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            :hamster: Looks good, @${{ github.actor }}!
